language: java
jdk:
  - openjdk11

branches:
  only:
    - master

####### 권한 추가 #######
before_install:
  - chmod +x gradlew

# Travis CI 서버의 홈
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동 후 전체 압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동 후 deploy  디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/blitz.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings 에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings 에 설정된 값
    bucket: blitz-springboot-build # S3 버킷
    region: ap-northeast-2
    edge: true
    acl: private # zip 파일 접근을 private 으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings 에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings 에 설정된 값
    bucket: blitz-springboot-build # S3 버킷
    key: blitz.zip
    bundle_type: zip  # 압축 확장자
    application: blitz-springboot-webservice # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: blitz-springboot-webservice-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - denhenker@naver.com
