spring:
  profiles:
    include: oauth,real-db
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
  session:
    store-type: jdbc
