spring:
  datasource:
    url: jdbc:mysql://blitz-database.cfplazddleqh.ap-northeast-2.rds.amazonaws.com:3306/blitz_test?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: Gkstmvns1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  mustache:
    suffix: .mustache
    prefix: classpath:/templates/
